################################################################################
## Resources
################################################################################
resources:
- name: gpdb-release
  type: git
  source:
    uri: {{gpdb-git-remote}}
    branch: ((gpdb-tag))

- name: debian-release
  type: git
  source:
    branch: master 
    uri: https://github.com/greenplum-db/debian-release.git

################################################################################
## Jobs
################################################################################

jobs:

- name: ppa-debian-release
  plan:
  - aggregate:
    - get: gpdb
      resource: gpdb-release
    - get: debian_release
      resource: debian-release
  - task: ppa-debian-release
    file: debian_release/concourse/tasks/ppa-debian-release.yml
    params:
      PPA_REPO: ((ppa-repository))
      GPG_PRIVATE_KEY: ((gpg-private-key))
      RELEASE_MESSAGE: ((release-message))
      DEBFULLNAME: ((debian-package-maintainer-fullname))
      DEBEMAIL: ((debian-package-maintainer-email))
