platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/ubuntu-gpdb-debian-dev
    tag: '16.04'
inputs:
  - name: gpdb
  - name: debian_release
    resource: debian-release

run:
  path: debian_release/concourse/scripts/ppa-debian-release.bash
